routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Auth::routes();

Route::prefix('devs')->group(function () {
    Route::get('/', 'AdminController@index')->name('pca');
    Route::resource('portfolios', 'portfoliosController');
    Route::resource('portfolio', 'PortfolioController');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/payment', 'PaymentController@widget')->name('payment');
Route::get('/payment/process', 'PaymentController@process')->name('process');

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'owner', 'developer_id', 'category_id'];
    public function category()
    {
      return $this->belongsTo('App\Category');
    }
    public function developer()
    {
      return $this->belongsTo('App\Developer');
    }
    public function image()
    {
        return $this->hasOne('App\PortfolioImage');
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Portfolio;
use App\PortfolioImage;
use App\Developer;
use App\Category;
use Storage;


class PortfolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $portfolios = Portfolio::all();
      return view('pca.portfolio.index', compact('portfolios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $developers = Developer::all();
        $categories = Category::all();
        return view('pca.portfolio.create', compact('developers', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path= $request->file('image')->store('portfolio', 'public');
        $url = Storage::url($path);
        $portfolio = new Portfolio();
        $portfolio->title = $request->title;
        $portfolio->description = $request->description;
        $portfolio->owner = $request->owner;
        $portfolio->developer_id = $request->developer_id;
        $portfolio->category_id = $request->category_id;
        $portfolio->save();
        $portfolioimage = new PortfolioImage();
        $portfolioimage->portfolio_id = $portfolio->id;
        $portfolioimage->src = $url;
        $portfolioimage->save();
        return redirect('devs/portfolio')->with('message', 'Se ha creado el portfolio correctamente haga <a href="'.url("/").'">click aquí</a> para verlo.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/portfoliosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Portfolio;
use Auth;
use Carbon\Carbon;

class portfoliosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('pca.portfolios.inicio');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pca.portfolios.nuevo');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Portfolio::create($request->all());

        return redirect('pca/portfolios')->with('message', 'Create un Portfolio.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $modelo = Portfolio::find($id);
        return view('pca.portfolios.ver', compact('modelo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $modelo = Portfolio::find($id);
        return view('pca.portfolios.editar', compact('modelo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $modelo = Portfolio::find($id);
        $modelo->updated_at = Carbon::now()->toDateTimeString();
        $modelo->save();
        $modelo->update($request->all());
        return redirect('pca/portfolios')->with('message', 'Editaste un Portfolio #'.$modelo->id.'.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $modelo = Portfolio::find($id);

        $modelo->delete();
        return redirect('pca/portfolios')->with('message', 'Borraste el Portfolio #'.$id.'.');
    }
}

resources/views/pca/portfolio/create.blade.php
@extends('layouts.admin')

@section('content')
  <div class="m-portlet m-portlet--tab">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <h3 class="m-portlet__head-text">Nuevo Portfolio</h3>
        </div>
      </div>
    </div>
    <form class="m-form m-form--fit m-form--label-align-right" action="{{route('portfolio.store')}}"  method="post" enctype="multipart/form-data">
      {{ csrf_field() }}
      {{ method_field('POST') }}
      <div class="m-portlet__body">
        <div class="form-group m-form__group">
          <label for="portada">
            Foto del proyecto
          </label>
          <div></div>
          <label class="custom-file">
            <input type="file" name="image" placeholder="Haga click para seleccionar un archivo" class="form-control-file">
          </label>
        </div>
        <div class="form-group m-form__group">
          <label for="title">Titulo</label>
          <input class="form-control m-input" type="text" name="title" value="">
          <span class="m-form__help">Escriba el titulo del proyecto.</span>
        </div>
        <div class="form-group m-form__group">
          <label for="description">Descripción</label>
          <textarea class="form-control m-textarea" name="description" rows="8" cols="80"></textarea>
          <span class="m-form__help">Escriba la descripción del proyecto.</span>
        </div>
        <div class="form-group m-form__group">
          <label for="owner">Dueño/Propietario</label>
          <input class="form-control m-input" type="text" name="owner" value="">
          <span class="m-form__help">Escriba el nombre del propietario del proyecto.</span>
        </div>
        <div class="form-group m-form__group">
          <label for="developer_id">Categoría</label>
          <select class="form-control m-select" name="category_id">
            @foreach ($categories as $category)
              <option value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
          </select>
          <span class="m-form__help">Seleccione la categoría del proyecto.</span>
        </div>
        <div class="form-group m-form__group">
          <label for="developer_id">Desarrollador</label>
          <select class="form-control m-select" name="developer_id">
            @foreach ($developers as $developer)
              <option value="{{$developer->id}}">{{$developer->alias}}</option>
            @endforeach
          </select>
        </div>
      </div>
      <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
          <button type="submit" class="btn btn-primary">Crear Portfolio</button>
        </div>
      </div>
    </form>
  </div>
@endsection
@section('scripts')
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=1ctd9ar2p0gqkcate7k6i1cyijcegdgbgfb4lw3gjth7ff32"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

resources/views/pca/portfolio/index.blade.php
@extends('layouts.admin')
@section('content')
  @if (session('message'))
    <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-brand alert-dismissible fade show" role="alert">
      <div class="m-alert__icon">
        <i class="flaticon-exclamation-1"></i>
        <span></span>
      </div>
      <div class="m-alert__text">
        <strong>{!! session('message') !!}</strong>
      </div>
      <div class="m-alert__close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"></button>
      </div>
    </div>
  @endif

  <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <h3 class="m-portlet__head-text">
            Portfolio
          </h3>
        </div>
      </div>
    </div>

    <div class="m-portlet__body">
      <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
        <div class="row align-items-center">
          <div class="col-xl-8 order-2 order-xl-1">
          </div>
          <div class="col-xl-4 order-1 order-xl-2 m--align-right">
            <a href="{{route('portfolio.create')}}" class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
              <span>
                <i class="la la-plus"></i>
                <span>
                  Crear Portfolio
                </span>
              </span>
            </a>
            <div class="m-separator m-separator--dashed d-xl-none"></div>
          </div>
        </div>
      </div>
      <table class="m-datatable" id="html_table" width="100%">
        <thead>
          <tr>
            <th title="#">
              #
            </th>
            <th title="Titulo">
              Titulo
            </th>
            <th title="Propietario">
              Propietario
            </th>
            <th title="Categoria">
              Categoría
            </th>
            <th title="Editar">
              Editar
            </th>
            <th title="Borrar">
              Borrar
            </th>
          </tr>
        </thead>
        <tbody>
          @foreach ($portfolios as $portfolio)
            <tr>
              <td>
                {{$portfolio->id}}
              </td>
              <td>
                {{$portfolio->title}}
              </td>
              <td>
                {{$portfolio->owner}}
              </td>
              <td>
                {{$portfolio->category->name}}
              </td>
              <td>
                <a href="{{route('portfolio.edit', ['id' => $portfolio->id])}}" class="btn btn-success m-btn m-btn--icon m-btn--icon-only"><i class="flaticon-edit-1"></i></a>
              </td>
              <td><form action="{{route('portfolio.destroy', ['id' => $portfolio->id])}}" method="post">{{ csrf_field() }}{{ method_field('delete') }}<button type="submit" class="btn btn-danger m-btn m-btn--icon m-btn--icon-only"><i class="flaticon-circle"></i></button></form></td>

            </tr>

          @endforeach

          </tbody>
        </table>

      </div>
    </div>
@endsection
@section('scripts')

  		<script src="{{asset('pca/demo/default/custom/components/datatables/base/html-table.js')}}" type="text/javascript"></script>
@endsection