routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Auth::routes();

Route::prefix('devs')->group(function () {
    Route::get('/', 'AdminController@index')->name('pca');
    Route::resource('portfolios', 'portfoliosController');
    Route::resource('portfolio', 'PortfolioController');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/payment', 'PaymentController@widget')->name('payment');
Route::get('/payment/process', 'PaymentController@process')->name('process');

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'owner', 'developer_id', 'category_id'];
    public function category()
    {
      return $this->belongsTo('App\Category');
    }
    public function developer()
    {
      return $this->belongsTo('App\Developer');
    }
    public function image()
    {
        return $this->hasOne('App\PortfolioImage');
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Portfolio;
use App\PortfolioImage;
use App\Developer;
use App\Category;
use Storage;


class PortfolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $portfolios = Portfolio::all();
      return view('pca.portfolio.index', compact('portfolios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $developers = Developer::all();
        $categories = Category::all();
        return view('pca.portfolio.create', compact('developers', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path= $request->file('image')->store('portfolio', 'public');
        $url = Storage::url($path);
        $portfolio = new Portfolio();
        $portfolio->title = $request->title;
        $portfolio->description = $request->description;
        $portfolio->owner = $request->owner;
        $portfolio->developer_id = $request->developer_id;
        $portfolio->category_id = $request->category_id;
        $portfolio->save();
        $portfolioimage = new PortfolioImage();
        $portfolioimage->portfolio_id = $portfolio->id;
        $portfolioimage->src = $url;
        $portfolioimage->save();
        return redirect('devs/portfolio')->with('message', 'Se ha creado el portfolio correctamente haga <a href="'.url("/").'">click aquí</a> para verlo.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/portfoliosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Portfolio;
use Auth;
use Carbon\Carbon;

class portfoliosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('pca.portfolios.inicio');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pca.portfolios.nuevo');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Portfolio::create($request->all());

        return redirect('pca/portfolios')->with('message', 'Create un Portfolio.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $modelo = Portfolio::find($id);
        return view('pca.portfolios.ver', compact('modelo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $modelo = Portfolio::find($id);
        return view('pca.portfolios.editar', compact('modelo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $modelo = Portfolio::find($id);
        $modelo->updated_at = Carbon::now()->toDateTimeString();
        $modelo->save();
        $modelo->update($request->all());
        return redirect('pca/portfolios')->with('message', 'Editaste un Portfolio #'.$modelo->id.'.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $modelo = Portfolio::find($id);

        $modelo->delete();
        return redirect('pca/portfolios')->with('message', 'Borraste el Portfolio #'.$id.'.');
    }
}

resources/views/pca/portfolios/editar.blade.php
@extends('layouts.admin')

@section('content')
  @php
    $columnas = Schema::getColumnListing('portfolios');
    $nombres = array();
    
$nombres = array_add($nombres, 'id', 'ID');
$nombres = array_add($nombres, 'title', 'Titulo');
$nombres = array_add($nombres, 'description', 'Descripcion');
$nombres = array_add($nombres, 'owner', 'Propietario');
$nombres = array_add($nombres, 'developer_id', 'Desarrollador');
$nombres = array_add($nombres, 'created_at', 'Creado');
$nombres = array_add($nombres, 'updated_at', 'Actualizado');
  @endphp
  <div class="m-portlet m-portlet--tab">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <h3 class="m-portlet__head-text">Editar Portfolio</h3>
        </div>
      </div>
    </div>
    <form class="m-form m-form--fit m-form--label-align-right" action="{{route('portfolios.update', ['id' => $modelo->id])}}"  method="post">
      {{ csrf_field() }}
      {{ method_field('PUT') }}
      <div class="m-portlet__body">
        @foreach ($columnas as $columna)
          @if ($columna != 'id' && $columna != 'created_at'&& $columna != 'updated_at')
            <div class="form-group m-form__group">
              <label for="p_es">{{$nombres[$columna]}}</label>
              <input class="form-control m-input" type="text" name="{{$columna}}" value="{{$modelo->$columna}}">
              <span class="m-form__help">Escriba el valor de: {{$nombres[$columna]}}</span>
            </div>
          @endif
        @endforeach


      </div>
      <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
          <button type="submit" class="btn btn-primary">Editar Portfolio</button>
        </div>
      </div>
    </form>
  </div>
@endsection

resources/views/pca/portfolios/inicio.blade.php
@extends('layouts.admin')
@section('content')
  @php
    $modelo = Portfolio::all();
    $columnas = Schema::getColumnListing('portfolios');
    $nombres = array();
    
$nombres = array_add($nombres, 'id', 'ID');
$nombres = array_add($nombres, 'title', 'Titulo');
$nombres = array_add($nombres, 'description', 'Descripcion');
$nombres = array_add($nombres, 'owner', 'Propietario');
$nombres = array_add($nombres, 'developer_id', 'Desarrollador');
$nombres = array_add($nombres, 'created_at', 'Creado');
$nombres = array_add($nombres, 'updated_at', 'Actualizado');
  @endphp

  @if (session('message'))
    <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-brand alert-dismissible fade show" role="alert">
      <div class="m-alert__icon">
        <i class="flaticon-exclamation-1"></i>
        <span></span>
      </div>
      <div class="m-alert__text">
        <strong>{!! session('message') !!}</strong>
      </div>
      <div class="m-alert__close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"></button>
      </div>
    </div>
  @endif

  <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <h3 class="m-portlet__head-text">
            Portfolio
          </h3>
        </div>
      </div>

    </div>
    <div class="m-portlet__body">
      <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
        <div class="row align-items-center">
          <div class="col-xl-8 order-2 order-xl-1">

          </div>
          <div class="col-xl-4 order-1 order-xl-2 m--align-right">
            <a href="{{route('portfolios.create')}}" class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
              <span>
                <i class="la la-plus"></i>
                <span>
                  Crear Portfolio
                </span>
              </span>
            </a>
            <div class="m-separator m-separator--dashed d-xl-none"></div>
          </div>
        </div>
      </div>
      <table class="m-datatable" id="html_table" width="100%">
        <thead>
          <tr>

            @foreach ($columnas as $columna)
              <th title="{{$nombres[$columna]}}">
                {{$nombres[$columna]}}
              </th>

            @endforeach
            <th title="Editar">
              Editar
            </th>
            <th title="Borrar">
              Borrar
            </th>

          </tr>
        </thead>
        <tbody>
          @foreach ($modelo as $mod)
            <tr>
              @foreach ($columnas as $columna)
                <td>
                  {{$mod->$columna}}
                </td>
              @endforeach

              <td>
                <a href="{{route('portfolios.edit', ['id' => $mod->id])}}" class="btn btn-success m-btn m-btn--icon m-btn--icon-only"><i class="flaticon-edit-1"></i></a>
              </td>
              <td><form action="{{route('portfolios.destroy', ['id' => $mod->id])}}" method="post">{{ csrf_field() }}{{ method_field('delete') }}<button type="submit" class="btn btn-danger m-btn m-btn--icon m-btn--icon-only"><i class="flaticon-circle"></i></button></form></td>

            </tr>

          @endforeach

          </tbody>
        </table>

      </div>
    </div>
    @endsection
    @section('scripts')
    <script src="{{asset('admin/assets/demo/default/custom/components/datatables/base/html-table.js')}}" type="text/javascript"></script>
    @endsection

resources/views/pca/portfolios/nuevo.blade.php
@extends('layouts.admin')

@section('content')
  @php
    $columnas = Schema::getColumnListing('portfolios');
    $nombres = array();
    
$nombres = array_add($nombres, 'id', 'ID');
$nombres = array_add($nombres, 'title', 'Titulo');
$nombres = array_add($nombres, 'description', 'Descripcion');
$nombres = array_add($nombres, 'owner', 'Propietario');
$nombres = array_add($nombres, 'developer_id', 'Desarrollador');
$nombres = array_add($nombres, 'created_at', 'Creado');
$nombres = array_add($nombres, 'updated_at', 'Actualizado');
  @endphp
  <div class="m-portlet m-portlet--tab">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <h3 class="m-portlet__head-text">Nuevo Portfolio</h3>
        </div>
      </div>
    </div>
    <form class="m-form m-form--fit m-form--label-align-right" action="{{route('portfolios.store')}}"  method="post">
      {{ csrf_field() }}
      {{ method_field('POST') }}
      <div class="m-portlet__body">
        @foreach ($columnas as $columna)
          @if ($columna != 'id' && $columna != 'created_at'&& $columna != 'updated_at')
            <div class="form-group m-form__group">
              <label for="{{$columna}}">{{$nombres[$columna]}}</label>
              <input class="form-control m-input" type="text" name="{{$columna}}" value="">
              <span class="m-form__help">Escriba el valor de: {{$nombres[$columna]}}</span>
            </div>
          @endif

        @endforeach

      </div>
      <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
          <button type="submit" class="btn btn-primary">Crear Portfolio</button>
        </div>
      </div>
    </form>
  </div>
@endsection